# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5843d343b6d70173121e563f22d126de0f3aa4d1b2ce29ed08ca63d86d68f4493a25bf4e0d53b49f8b044bf0e412451426ec2efe86209b28a56a9c863ac3046b

test:
  secret_key_base: 39a11a8a9aee5df07bb41e93a1e9073bab4245c7c2cf4caead6d6d7aea8cde7810d4d722f0d9ae3e03cdb6873f0cef2e0f9bdcd00a6a86f6a05f86915cddb999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
